const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('plumbago', {
  getContext: () => ipcRenderer.invoke('plumbago:get-context'),
  chooseBlog: () => ipcRenderer.invoke('plumbago:choose-blog'),
  createBlog: (input) => ipcRenderer.invoke('plumbago:create-blog', input),
  listThemes: () => ipcRenderer.invoke('plumbago:list-themes'),
  installTheme: (slug) => ipcRenderer.invoke('plumbago:install-theme', slug),
  siteSettings: () => ipcRenderer.invoke('plumbago:site-settings'),
  saveSiteSettings: (input) => ipcRenderer.invoke('plumbago:save-site-settings', input),
  openTheme: (slug) => ipcRenderer.invoke('plumbago:open-theme', slug),
  listPosts: () => ipcRenderer.invoke('plumbago:list-posts'),
  readPost: (id) => ipcRenderer.invoke('plumbago:read-post', id),
  savePost: (post) => ipcRenderer.invoke('plumbago:save-post', post),
  createPost: (input) => ipcRenderer.invoke('plumbago:create-post', input),
  importImages: (postId) => ipcRenderer.invoke('plumbago:import-images', postId),
  importDroppedImages: (postId, files) => {
    const sourcePaths = files.map((file) => webUtils.getPathForFile(file)).filter(Boolean)
    return ipcRenderer.invoke('plumbago:import-image-paths', postId, sourcePaths)
  },
  readAsset: (postId, name) => ipcRenderer.invoke('plumbago:read-asset', postId, name),
  readAssetInfo: (postId, name) => ipcRenderer.invoke('plumbago:read-asset-info', postId, name),
  gitStatus: () => ipcRenderer.invoke('plumbago:git-status'),
  gitConfig: () => ipcRenderer.invoke('plumbago:git-config'),
  saveGitConfig: (config) => ipcRenderer.invoke('plumbago:save-git-config', config),
  syncGit: (message) => ipcRenderer.invoke('plumbago:sync-git', message),
  publishingStatus: () => ipcRenderer.invoke('plumbago:publishing-status'),
  publishBlog: (message) => ipcRenderer.invoke('plumbago:publish-blog', message),
  openPublishingUrl: (url) => ipcRenderer.invoke('plumbago:open-publishing-url', url),
  githubStatus: () => ipcRenderer.invoke('plumbago:github-status'),
  beginGitHubSignIn: () => ipcRenderer.invoke('plumbago:github-begin-sign-in'),
  completeGitHubSignIn: (deviceCode) => ipcRenderer.invoke('plumbago:github-complete-sign-in', deviceCode),
  connectGitHubToken: (token) => ipcRenderer.invoke('plumbago:github-connect-token', token),
  disconnectGitHub: () => ipcRenderer.invoke('plumbago:github-disconnect'),
  listGitHubRepositories: () => ipcRenderer.invoke('plumbago:github-repositories'),
  createGitHubRepository: (input) => ipcRenderer.invoke('plumbago:github-create-repository', input),
  connectGitHubRepository: (fullName, protocol) => ipcRenderer.invoke('plumbago:github-connect-repository', fullName, protocol),
  configureGitHubPages: () => ipcRenderer.invoke('plumbago:github-configure-pages'),
  publishingHealth: () => ipcRenderer.invoke('plumbago:publishing-health'),
  chooseBloggerExport: () => ipcRenderer.invoke('plumbago:choose-blogger-export'),
  importBloggerExport: (options) => ipcRenderer.invoke('plumbago:import-blogger-export', options),
  openPreview: () => ipcRenderer.invoke('plumbago:open-preview'),
})
