const fs = require('node:fs/promises')
const path = require('node:path')
const { createRecoveryPoint, restoreRecoveryPoint, siteConfigurationPaths } = require('../history.cjs')
const {
  deleteGitHubActionsSecret,
  githubAuthorizationStatus,
  githubPagesWorkflow,
  githubWorkflowRunStatus,
  parseGitHubRemote,
  saveGitHubActionsSecret,
  triggerGitHubWorkflow,
} = require('../github.cjs')
const { configureGitHubPages, gitStatus, syncGit } = require('../publishing.cjs')
const { deploymentSettings, hostingSettings, siteMetadata, updateSiteConfig, validateBlog } = require('../site.cjs')
const { safeWorkflowTimeZone } = require('./workflow-time.cjs')

const WORKFLOWS = {
  'github-pages': 'plumbago-pages.yml',
  'cloudflare-pages': 'plumbago-cloudflare-pages.yml',
}

function workflowRelative(provider) {
  const file = WORKFLOWS[provider]
  if (!file) throw new Error('Scheduled publishing supports GitHub Pages or Cloudflare Pages.')
  return `.github/workflows/${file}`
}

function workflowAbsolute(root, provider) {
  const workflows = path.resolve(root, '.github', 'workflows')
  const target = path.resolve(workflows, WORKFLOWS[provider] || '')
  if (!WORKFLOWS[provider] || path.dirname(target) !== workflows) throw new Error('The scheduled publishing workflow path is invalid.')
  return target
}

function cloudflareWorkflow(input = {}) {
  const branch = /^[A-Za-z0-9._/-]+$/.test(String(input.branch || '')) ? String(input.branch) : 'main'
  const projectName = String(input.projectName || '')
  if (!/^[a-z0-9][a-z0-9-]{0,57}[a-z0-9]$|^[a-z0-9]$/i.test(projectName)) throw new Error('The Cloudflare Pages project name is invalid.')
  let liveUrl
  try { liveUrl = new URL(input.liveUrl).href } catch { throw new Error('The Cloudflare Pages public address is invalid.') }
  if (new URL(liveUrl).protocol !== 'https:') throw new Error('The Cloudflare Pages public address must use HTTPS.')
  const hugoVersion = /^\d+\.\d+\.\d+$/.test(String(input.hugoVersion || '')) ? String(input.hugoVersion) : '0.128.0'
  const branches = [...new Set(['main', 'master', branch])].map((name) => `      - ${JSON.stringify(name)}`).join('\n')
  return `# Generated by Plumbago. The Cloudflare token is stored only as an encrypted GitHub Actions secret.
name: Publish scheduled Hugo content to Cloudflare Pages

on:
  push:
    branches:
${branches}
  schedule:
    - cron: "13,43 * * * *"
      timezone: ${JSON.stringify(safeWorkflowTimeZone(input.timeZone))}
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: plumbago-cloudflare-pages
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DART_SASS_VERSION: 1.101.0
      HUGO_VERSION: ${hugoVersion}
      NODE_VERSION: 24
    steps:
      - name: Check out blog
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: \${{ env.NODE_VERSION }}
      - name: Install Hugo Extended
        run: |
          curl -sfL -o \${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v\${HUGO_VERSION}/hugo_extended_\${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i \${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: |
          mkdir -p "\${HOME}/.local"
          curl -sfL -o \${{ runner.temp }}/dart-sass.tar.gz https://github.com/sass/dart-sass/releases/download/\${DART_SASS_VERSION}/dart-sass-\${DART_SASS_VERSION}-linux-x64.tar.gz
          tar -C "\${HOME}/.local" -xf \${{ runner.temp }}/dart-sass.tar.gz
          echo "\${HOME}/.local/dart-sass" >> "\${GITHUB_PATH}"
      - name: Install Node.js dependencies when present
        if: hashFiles('package-lock.json') != ''
        run: npm ci
      - name: Build the due version
        env:
          HUGO_CACHEDIR: \${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: hugo --gc --minify --baseURL ${JSON.stringify(liveUrl)}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=${projectName} --branch=\${{ github.ref_name }}
          gitHubToken: \${{ secrets.GITHUB_TOKEN }}
`
}

async function automationStatus(root, credentials = {}) {
  const [metadata, git] = await Promise.all([siteMetadata(root), gitStatus(root).catch(() => ({ branch: '', remote: '' }))])
  const hosting = await hostingSettings(root, metadata.baseURL)
  const provider = hosting.hostingProvider
  const supported = Object.hasOwn(WORKFLOWS, provider)
  const repository = parseGitHubRemote(git.remote)
  if (!supported) return { provider, supported: false, enabled: false, workflow: '', repository, timeZone: metadata.timeZone || '', lastRun: { state: 'unavailable' } }
  const workflow = workflowRelative(provider)
  const raw = await fs.readFile(workflowAbsolute(root, provider), 'utf8').catch(() => '')
  const enabled = /\n\s*schedule\s*:/m.test(raw)
  const intervalMinutes = /cron:\s*["']13,43 \* \* \* \*["']/.test(raw) ? 30 : enabled ? 60 : 30
  const lastRun = repository && credentials.githubToken && raw
    ? await githubWorkflowRunStatus(credentials.githubToken, repository, WORKFLOWS[provider])
    : { state: raw ? 'unavailable' : 'not-configured', conclusion: '', runUrl: '', updatedAt: '' }
  return { provider, supported: true, enabled, workflow, repository, branch: git.branch || 'main', timeZone: metadata.timeZone || '', intervalMinutes, lastRun }
}

async function requireAutomationRepository(root, token) {
  if (!token) throw new Error('Connect GitHub before enabling background publishing.')
  const authorization = await githubAuthorizationStatus(token)
  if (!authorization.repository || !authorization.workflow) throw new Error('Reconnect GitHub with repository and workflow permissions before enabling background publishing.')
  const git = await gitStatus(root)
  const repository = parseGitHubRemote(git.remote)
  if (!repository) throw new Error('Connect this blog to a GitHub repository first.')
  return { git, repository }
}

async function enableAutomation(root, input = {}, credentials = {}) {
  const provider = String(input.provider || (await hostingSettings(root, (await siteMetadata(root)).baseURL)).hostingProvider)
  if (!Object.hasOwn(WORKFLOWS, provider)) throw new Error('Choose GitHub Pages or Cloudflare Pages before enabling background publishing.')
  const { git, repository } = await requireAutomationRepository(root, credentials.githubToken)
  const context = await validateBlog(root)
  const metadata = await siteMetadata(root)
  const timeZone = safeWorkflowTimeZone(input.timeZone || metadata.timeZone)
  const relative = workflowRelative(provider)
  const recoveryPoint = await createRecoveryPoint(root, { reason: 'before-calendar-automation', label: 'Before enabling background publishing', paths: [...await siteConfigurationPaths(root), relative] })
  const cloudflareSecretsWritten = []
  try {
    if (metadata.timeZone !== timeZone) await updateSiteConfig(root, { timeZone })
    if (provider === 'github-pages') {
      await configureGitHubPages(root, credentials.githubToken)
    } else {
      if (!credentials.cloudflareToken) throw new Error('Connect Cloudflare before enabling scheduled Direct Upload.')
      const deployment = await deploymentSettings(root)
      if (!deployment.accountId || !deployment.projectName || !deployment.liveUrl) throw new Error('Complete one Cloudflare Pages deployment before enabling scheduled publishing.')
      const contents = cloudflareWorkflow({
        branch: git.branch,
        projectName: deployment.projectName,
        liveUrl: deployment.liveUrl,
        hugoVersion: context.hugo?.match(/hugo v(\d+\.\d+\.\d+)/i)?.[1],
        timeZone,
      })
      const target = workflowAbsolute(root, provider)
      await fs.mkdir(path.dirname(target), { recursive: true })
      await fs.writeFile(target, contents, 'utf8')
      await saveGitHubActionsSecret(credentials.githubToken, repository, 'CLOUDFLARE_ACCOUNT_ID', deployment.accountId)
      cloudflareSecretsWritten.push('CLOUDFLARE_ACCOUNT_ID')
      await saveGitHubActionsSecret(credentials.githubToken, repository, 'CLOUDFLARE_API_TOKEN', credentials.cloudflareToken)
      cloudflareSecretsWritten.push('CLOUDFLARE_API_TOKEN')
    }
    await syncGit(root, 'Enable scheduled publishing with Plumbago', { githubToken: credentials.githubToken })
    return { ...await automationStatus(root, credentials), recoveryPoint }
  } catch (error) {
    await restoreRecoveryPoint(root, recoveryPoint.id, { createUndo: false }).catch(() => {})
    await Promise.all(cloudflareSecretsWritten.map((name) => deleteGitHubActionsSecret(credentials.githubToken, repository, name))).catch(() => {})
    throw error
  }
}

async function disableAutomation(root, credentials = {}) {
  const current = await automationStatus(root, credentials)
  if (!current.supported || !current.repository) throw new Error('No supported scheduled publishing workflow is configured.')
  const { git, repository } = await requireAutomationRepository(root, credentials.githubToken)
  const relative = workflowRelative(current.provider)
  const recoveryPoint = await createRecoveryPoint(root, { reason: 'before-calendar-automation', label: 'Before disabling background publishing', paths: [relative] })
  try {
    if (current.provider === 'github-pages') {
      const context = await validateBlog(root)
      const metadata = await siteMetadata(root)
      await fs.writeFile(workflowAbsolute(root, current.provider), githubPagesWorkflow(git.branch, context.hugo?.match(/hugo v(\d+\.\d+\.\d+)/i)?.[1], { timeZone: metadata.timeZone, scheduled: false }), 'utf8')
    } else {
      await fs.rm(workflowAbsolute(root, current.provider), { force: true })
    }
    await syncGit(root, 'Disable scheduled publishing with Plumbago', { githubToken: credentials.githubToken })
  } catch (error) {
    await restoreRecoveryPoint(root, recoveryPoint.id, { createUndo: false }).catch(() => {})
    throw error
  }
  let warning = ''
  if (current.provider === 'cloudflare-pages') {
    await Promise.all([
      deleteGitHubActionsSecret(credentials.githubToken, repository, 'CLOUDFLARE_ACCOUNT_ID'),
      deleteGitHubActionsSecret(credentials.githubToken, repository, 'CLOUDFLARE_API_TOKEN'),
    ]).catch((error) => { warning = `The workflow was disabled, but GitHub could not remove the old Cloudflare secrets: ${error.message}` })
  }
  return { ...await automationStatus(root, credentials), recoveryPoint, warning }
}

async function runAutomationNow(root, credentials = {}) {
  const current = await automationStatus(root, credentials)
  if (!current.enabled || !current.repository) throw new Error('Enable background publishing before running it now.')
  await triggerGitHubWorkflow(credentials.githubToken, current.repository, WORKFLOWS[current.provider], current.branch)
  return { ...current, requestedAt: new Date().toISOString() }
}

module.exports = { automationStatus, cloudflareWorkflow, disableAutomation, enableAutomation, runAutomationNow, workflowRelative }
