const { fetchJson, githubRequest, postForm } = require('../core/http.cjs')
const { run } = require('../core/runtime.cjs')

async function beginGitHubSignIn(clientId) {
  if (!clientId) throw new Error('GitHub sign-in is not configured in this Plumbago build.')
  return postForm('https://github.com/login/device/code', { client_id: clientId, scope: 'repo read:user user:email' })
}

async function completeGitHubSignIn(clientId, deviceCode) {
  const payload = await postForm('https://github.com/login/oauth/access_token', {
    client_id: clientId,
    device_code: deviceCode,
    grant_type: 'urn:ietf:params:oauth:grant-type:device_code',
  })
  if (payload.access_token) return { state: 'complete', token: payload.access_token, scope: payload.scope || '' }
  const states = {
    authorization_pending: 'pending',
    slow_down: 'slow-down',
    expired_token: 'expired',
    access_denied: 'denied',
  }
  return { state: states[payload.error] || 'error', description: payload.error_description || '' }
}

async function githubAccount(token) {
  const account = await githubRequest(token, '/user')
  return {
    login: account.login,
    name: account.name || account.login,
    avatarUrl: account.avatar_url,
    profileUrl: account.html_url,
  }
}

async function githubCliToken(root) {
  return run(root, 'gh', ['auth', 'token', '--hostname', 'github.com']).then((result) => result.stdout)
}

async function listGitHubRepositories(token) {
  const repositories = await githubRequest(token, '/user/repos?affiliation=owner%2Ccollaborator%2Corganization_member&sort=updated&per_page=100')
  return repositories.map((repository) => ({
    fullName: repository.full_name,
    name: repository.name,
    owner: repository.owner.login,
    private: repository.private,
    url: repository.html_url,
    sshUrl: repository.ssh_url,
    cloneUrl: repository.clone_url,
    permissions: repository.permissions || {},
  }))
}

function parseGitHubRemote(remote) {
  const value = String(remote || '').trim()
  let match = value.match(/^git@github\.com:([^/\s]+)\/([^/\s]+?)(?:\.git)?$/i)
  if (!match) match = value.match(/^(?:ssh|https?):\/\/(?:git@)?github\.com\/([^/\s]+)\/([^/\s]+?)(?:\.git)?\/?$/i)
  if (!match) return null
  const owner = match[1]
  const repository = match[2].replace(/\.git$/i, '')
  if (!/^[\w.-]+$/.test(owner) || !/^[\w.-]+$/.test(repository)) return null
  return {
    owner,
    repository,
    fullName: `${owner}/${repository}`,
    url: `https://github.com/${owner}/${repository}`,
  }
}

function defaultGitHubPagesUrl(repository) {
  if (!repository) return ''
  return repository.repository.toLowerCase() === `${repository.owner.toLowerCase()}.github.io`
    ? `https://${repository.owner}.github.io/`
    : `https://${repository.owner}.github.io/${repository.repository}/`
}

function githubPagesWorkflow(branch, hugoVersion) {
  return `# Generated by Plumbago. You can customize this workflow at any time.
name: Deploy Hugo site to Pages

on:
  push:
    branches: [${JSON.stringify(branch)}]
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DART_SASS_VERSION: 1.101.0
      HUGO_VERSION: ${hugoVersion}
      NODE_VERSION: 24
    steps:
      - name: Check out blog
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v6
      - name: Install Node.js when needed
        if: hashFiles('package-lock.json') != ''
        uses: actions/setup-node@v6
        with:
          node-version: \${{ env.NODE_VERSION }}
      - name: Install Dart Sass
        run: |
          mkdir -p "\${HOME}/.local"
          curl -sfL -o \${{ runner.temp }}/dart-sass.tar.gz https://github.com/sass/dart-sass/releases/download/\${DART_SASS_VERSION}/dart-sass-\${DART_SASS_VERSION}-linux-x64.tar.gz
          tar -C "\${HOME}/.local" -xf \${{ runner.temp }}/dart-sass.tar.gz
          echo "\${HOME}/.local/dart-sass" >> "\${GITHUB_PATH}"
      - name: Install Hugo Extended
        run: |
          curl -sfL -o \${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v\${HUGO_VERSION}/hugo_extended_\${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i \${{ runner.temp }}/hugo.deb
      - name: Install Node.js dependencies when present
        if: hashFiles('package-lock.json') != ''
        run: npm ci
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: \${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: hugo --gc --minify --baseURL "\${{ steps.pages.outputs.base_url }}/"
      - name: Upload website
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish website
        id: deployment
        uses: actions/deploy-pages@v5
`
}

async function githubWorkflowStatus(repository, branch) {
  if (!repository) return { state: 'unavailable', conclusion: '', runUrl: '', updatedAt: '' }
  try {
    const query = new URLSearchParams({ per_page: '30' })
    if (branch) query.set('branch', branch)
    const response = await fetchJson(`https://api.github.com/repos/${repository.owner}/${repository.repository}/actions/runs?${query}`)
    const candidates = response.workflow_runs || []
    const workflow = candidates.find((item) => /pages|deploy|hugo|publish/i.test(`${item.name} ${item.path}`))
    if (!workflow) return { state: 'not-configured', conclusion: '', runUrl: '', updatedAt: '' }
    const active = ['queued', 'in_progress', 'requested', 'waiting', 'pending'].includes(workflow.status)
    const state = active ? 'deploying' : workflow.conclusion === 'success' ? 'live' : 'failed'
    return {
      state,
      conclusion: workflow.conclusion || '',
      runUrl: workflow.html_url || '',
      updatedAt: workflow.updated_at || workflow.created_at || '',
      name: workflow.name || '',
    }
  } catch {
    return { state: 'unknown', conclusion: '', runUrl: '', updatedAt: '' }
  }
}

module.exports = {
  beginGitHubSignIn,
  completeGitHubSignIn,
  defaultGitHubPagesUrl,
  githubAccount,
  githubCliToken,
  githubPagesWorkflow,
  githubWorkflowStatus,
  listGitHubRepositories,
  parseGitHubRemote,
}
